### ISSUE TITLE
Create more examples on how to use autopytorch

### ISSUE THREAD

**Issue by franchuterivera** [automl/Auto-PyTorch#111]
Create a directory structure with basic and advanced examples that include:

- [x] How to customize the pipeline and search space. Also add only desired classifiers.

**Comment by ravinkohli** [comment]
We can do this in two approaches in my opinion, 1) create a single example file where we explain all possible modifications that can be made to the search. 2) create a separate file for the modifications (maybe splitting to separate files if necessary) and also have a vanilla run file. Which of these approaches would you prefer? I am leaning towards the second one.

**Comment by franchuterivera** [comment]
Yes I am inclined to this directory structure:
```
tabular/20_basics/
- example_tabular_classification.py
- example_tabular_regression.py
tabular/40_advanced/
- example_custom_configuration_space.py
- example_resampling_strategies.py
```

What do you think? What else we can add?

**Comment by ravinkohli** [comment]
yeah I'll do it this way then. Also, is there any reason for using 20 and 40? I cant think of anything more right now. I'll update here if something comes to mind.
