### ISSUE TITLE
Does the architecture support model checkpointing? If yes, is it already implemented

### ISSUE THREAD

**Issue by etetteh** [automl/Auto-PyTorch#12]

**Comment by LMZimmer** [comment]
Hey there,

are you looking for a way to save the state of the search to continue it at a later point or do you mean creating checkpoints during refitting a single architecture?

Best, Lucas

**Comment by etetteh** [comment]
I mean the latter. Creating checkpoints during refitting.

Luca, it's been a while.

**Comment by LMZimmer** [comment]
I am sorry but the current version does not support checkpoints.
