### ISSUE TITLE
Handle determinism in the pipeline

### ISSUE THREAD

**Issue by ravinkohli** [automl/Auto-PyTorch#137]
This issue is being moved from the old repository. Look [here](https://github.com/LMZimmer/Auto-PyTorch_refactor/issues/10) for more details. 
Description:
we need to add support for setting seeds for various random number generations. Could be handled once in the api for the whole project or individually for pipeline components.

@LMZimmer suggested: 
For this let's:

    1. create a set_random_state in the BasePipeline
    2. call it in the init after [this](https://github.com/automl/Auto-PyTorch/blob/5c6ce0bbf030fb4ec81396e1cb67edb3e194d383/autoPyTorch/pipeline/base_pipeline.py#L104)

add support for this in the smbo part and pass the state to the pipeline

**Comment by renesass** [comment]
Moreover, as far as I can see, random state is not used for the train data loader (in base_data_loader), which uses shuffling. Correct me if I'm wrong.

**Comment by ravinkohli** [comment]
> Moreover, as far as I can see, random state is not used for the train data loader (in base_data_loader), which uses shuffling. Correct me if I'm wrong.

Yes that is true. Thanks for pointing this out
