### ISSUE TITLE
Many Dicts in the codes are not understandable.

### ISSUE THREAD

**Issue by nabenabe0928** [automl/Auto-PyTorch#140]
As in the title, many dicts in the codes are not understandable.

For example, what does `named_steps` in base_pipeline.py mean?

To address this problem, I would like to promote the usage of either [BaseNamedTuple](https://github.com/automl/Auto-PyTorch/pull/139) or [BaseDict](https://github.com/automl/Auto-PyTorch/pull/138).

I felt the following problems regarding the current usage of dicts:
1. When we use a dict in various locations, it is not clear what variables should be included in the dict (or tuple).
2. The definition of each variable is not clear.
3. It is likely to cause a lot of typo, because we cannot have the benefit of the autocompletion functionality from editors (e.g. vscode).

The new rules for this usage are the followings:
1. Define BaseDict or BaseNamedTuple in the head of each file if we need to use ad-hoc dicts
2. Write the locations (which files) of doc-string for each dict or NamedTuple for better understandings
3. Use attribute and avoid string keys (i.e. use `d.foo` instead of `d["foo"]`)

About the last statement (use attributes), that is because it is easier to prevent typo by the autocompletion.

For these reasons, I have introduced `BaseDict` and `BaseNamedTuple`.
Basically, when we would like to have variables with immutable state, we use `BaseNamedTuple` and otherwise we use `BaseDict`.

Both modules can be used by `from autoPytorch.common import create_dictlike_namedtuple, BaseDict`.

The declaration for each module is the following:
```
class menu(NamedTuple):
     fish: int = 5
     meat: int = 10
     drink: int = 7

today = create_dictlike_namedtuple(menu, fish=3, meat=13)
for key, value in today.items():
     print(key, value)
print(today)

[out]
fish 3
meat 13
drink 7
WrapedNamedTuple(fish=3, meat=13, drink=7)
```

```
class NewDict(BaseDict):
     a: int = 3
     b: float = 2.0
     c: str

new_dict = NewDict(a=1, d=5)
print(new_dict)
print(new_dict.a, new_dict.b, new_dict.c, new_dict.d)

[out]        
{'a': 1, 'd': 5, 'b': 2.0, 'c': None}
1 2.0 None 5
```

**Comment by nabenabe0928** [comment]
I found out [dataclasses](https://docs.python.org/3/library/dataclasses.html) are the good solution for this.

I will replace most `NamedTuple` and `dict` with `dataclasses` in the near future.

**Comment by ravinkohli** [comment]
Hey @nabenabe0928, named_steps is an attribute coming from sklearn pipelines. Other than that could you give an example of where it can be used currently in our code? I personally cant think of a place
