### ISSUE TITLE
Possible OpenML Version Mismatch

### ISSUE THREAD

**Issue by NeoChaos12** [automl/Auto-PyTorch#158]
Hi,

I was trying to setup Auto-PyTorch to use with the benchmarking module and re-create some of the experiments from the paper. While testing out individual modules of the library, I ran into what is probably a mismatch between the OpenML version indicated in the requirements.txt of the repo and the API expected by the code. The following is a minimum working example of this:

> `from autoPyTorch.data_management.data_reader import OpenMlReader`
> /home/archit/miniconda3/envs/autopytorch/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
>   warnings.warn(message, FutureWarning)
> 
> `reader = OpenMlReader(dataset_id=31)`
> `reader.read()`
> Traceback (most recent call last):
>   File "/home/archit/thesis/Auto-PyTorch/autoPyTorch/data_management/data_reader.py", line 113, in read
>     self.X, self.Y, self.categorical_features = dataset.get_data(
>                 target=dataset.default_target_attribute, return_categorical_indicator=True)
> TypeError: get_data() got an unexpected keyword argument 'return_categorical_indicator'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/archit/miniconda3/envs/autopytorch/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-4-4010e1836910>", line 1, in <module>
>     reader.read()
>   File "/home/archit/thesis/Auto-PyTorch/autoPyTorch/data_management/data_reader.py", line 116, in read
>     raise RuntimeError("An error occurred when loading the dataset and splitting it into X and Y. Please check if the dataset is suitable.")
> RuntimeError: An error occurred when loading the dataset and splitting it into X and Y. Please check if the dataset is suitable.
>

I then cross-validated my OpenML installation as well the API of the said installation, and the offending parameter is indeed missing from the API:

> `import openml`
> `openml.__version__`
> Out[6]: '0.11.0'
> `import inspect`
> `inspect.signature(openml.OpenMLDataset.get_data)`
> Out[8]: <Signature (self, target: Union[List[str], str, NoneType] = None, include_row_id: bool = False, include_ignore_attribute: bool = False, dataset_format: str = 'dataframe') -> Tuple[Union[numpy.ndarray, pandas.core.frame.DataFrame, scipy.sparse.csr.csr_matrix], Union[numpy.ndarray, pandas.core.frame.DataFrame, NoneType], List[bool], List[str]]>
> 

I checked the OpenML documentation as well as the source code, and the current master does use the API visible via `inspect.signature`, although the official [cheat sheet](https://openml.github.io/openml-tutorial/slides_pdf/OpenML%20Python%20cheat%20sheet.pdf) PDF uses the same API as is being used in autoPyTorch. This leads me to believe that at some of point of time, a backwards-incompatible change has been implemented in OpenML's Python API, but I could not immediately find something to that effect in their [changelog](https://openml.github.io/openml-python/master/progress.html), except for a brief mention to something that might be unrelated in 0.9.0.

Some context for my environment:
OS: Ubuntu 18.04
Python: 3.8.8
Conda: 4.9.2
AutoPyTorch: latest master as of writing (commit 7c95381d5345498ddbe026d3b8b8ae41264644c9)

As a control, I also created a fresh conda environment with a slightly older (but known to be stabler) python version (`conda create -n test python=3.6`) on a different machine running Ubuntu 20.04, and tried checking just the API of `openml==0.11.0`, and was given identical results:

> `import openml`
> `import inspect`
> `openml.__version__`
> '0.11.0'
> `inspect.signature(openml.OpenMLDataset.get_data)`
> <Signature (self, target:Union[List[str], str, NoneType]=None, include_row_id:bool=False, include_ignore_attribute:bool=False, dataset_format:str='dataframe') -> Tuple[Union[numpy.ndarray, pandas.core.frame.DataFrame, scipy.sparse.csr.csr_matrix], Union[numpy.ndarray, pandas.core.frame.DataFrame, NoneType], List[bool], List[str]]>
> 

I am, unfortunately, not very familiar with the OpenML API and some searching on my behalf did not immediately turn up the correct version, so I am unable to offer any immediate fixes. I hope this can be resolved soon. Thank you!

**Comment by ravinkohli** [comment]
Hey, we have added a requirements.txt file in the master branch as well. Therefore, I'm closing this issue
