### ISSUE TITLE
Remove user-defined splitting

### ISSUE THREAD

**Issue by nabenabe0928** [automl/Auto-PyTorch#159]
The current example looks like the following:
```
    X, y = sklearn.datasets.fetch_openml(name='boston', return_X_y=True, as_frame=True)
    X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
        X,
        y,
        random_state=1,
    )

    # Scale the regression targets to have zero mean and unit variance.
    # This is important for Neural Networks since predicting large target values would require very large weights.
    # One can later rescale the network predictions like this: y_pred = y_pred_scaled * y_train_std + y_train_mean
    y_train_mean = y_train.mean()
    y_train_std = y_train.std()

    y_train_scaled = (y_train - y_train_mean) / y_train_std
    y_test_scaled = (y_test - y_train_mean) / y_train_std

    ############################################################################
    # Build and fit a regressor
    # ==========================
    api = TabularRegressionTask(
        temporary_directory='./tmp/autoPyTorch_example_tmp_02',
        output_directory='./tmp/autoPyTorch_example_out_02',
        # To maintain logs of the run, set the next two as False
        delete_tmp_folder_after_terminate=True,
        delete_output_folder_after_terminate=True
    )
```

However, it may cause the memory leak issue because we store both `X` and `X_train, X_test`.
For this reason, I would like to change this part to prevent a further memory leak.
In any case, we currently do not use the test dataset in the `BaseDataset` class,
so it does not affect the code so much or even better.

**Comment by ravinkohli** [comment]
I think the goal of the example, is to provide the user with an easy to follow description of how to use the library. And btw, I disagree with the statement `In any case, we currently do not use the test dataset in the BaseDataset class`. It is used in the `AbstractEvaluator` (see [here](https://github.com/automl/Auto-PyTorch/blob/eda89f444611fd03767242ae0f12c294540e5f01/autoPyTorch/evaluation/abstract_evaluator.py#L444)) where it can be used to extract the test curves and eventually it is also used to calculate the run summary in the pipeline. Therefore, I would close this issue. Feel free to reopen this in case you want to discuss further
