### ISSUE TITLE
Issues running on Regression dataset

### ISSUE THREAD

**Issue by alexvicegrab** [automl/Auto-PyTorch#16]
When running on a Regression dataset with default inputs (i.e. as per your Classification example, but using AutoNetRegression instead), I see an error as follows:

    ValueError: Config option loss_modules contains following invalid values {'cross_entropy_weighted'}, chose a subset of ['l1_loss']

However, it would be ideal if the default set of loss_modules for the regression is only the permissible losses :)

**Comment by LMZimmer** [comment]
You are right, this should not happen. Thank you for the input!

**Comment by alexvicegrab** [comment]
Additionally, I see some other issues, such as my outputs (Y) being treated as inputs (X) during the auto-regression.

**Comment by alexvicegrab** [comment]
```
/site-packages/autoPyTorch/pipeline/nodes/imputation.py", line 48, in predict
    X = X[:, ~all_nan_columns]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1 but corresponding boolean dimension is 17
```

**Comment by LMZimmer** [comment]
Could you provide a minimal example or the complete traceback?
