### ISSUE TITLE
Yield extremely high memory consumption when feeding ndarray

### ISSUE THREAD

**Issue by nabenabe0928** [automl/Auto-PyTorch#163]
In `example_tabular_classfiication.py`, when we use:
```
import numpy as np

N, D = 5 * 10 ** 5, 80  # the same size as albert 
X, y = np.random.random((N, D)), np.random.randint(2, size=(N, 1))
```
instead of:
```
import openml

id = 41147  # albert
dataset = openml.datasets.get_dataset(id)
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)
```
We obtain extremely high memory consumption (around 5GB) in the first example.
However, when we do:
```
X, y = pd.DataFrame(X), pd.DataFrame(y)
```
It reduces the memory consumption (around 3GB).
Probably, we should consider it once.

**Comment by ravinkohli** [comment]
aren't we converting the numpy array to pandas already in the tabular feature validator? see [here](https://github.com/automl/Auto-PyTorch/blob/bf264d67e310e7d6c37ed4b7f5355264f716f82b/autoPyTorch/data/tabular_feature_validator.py#L140). If so, could you please close the issue?
