### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by loveunk** [automl/Auto-PyTorch#181]
After installing the latest version of Auto-Pytorch, I got the following errors:
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

Someone suggests to upgrade `numpy` with version >= 1.20.0.

I tried with `pip install numpy==1.20.1` and it works.

**Comment by minsikseo-cdl** [comment]
I have the same issue.
By the way, ```pip check``` says ```autopytorch 0.0.2 has requirement numpy==1.19.5, but you have numpy 1.20.1.```.
Is it okay to ignore it?

**Comment by loveunk** [comment]
> I have the same issue.
> By the way, `pip check` says `autopytorch 0.0.2 has requirement numpy==1.19.5, but you have numpy 1.20.1.`.
> Is it okay to ignore it?

It's OK to ignore the warning.
