### ISSUE TITLE
DataType Error?

### ISSUE THREAD

**Issue by yashlal** [automl/Auto-PyTorch#216]
My X input is a valid numpy array of float values between 0 and 1 and Y input is integers (0 or 1) and the AutoNetClassifier is yielding the following warning which subsequently becomes an error: 

**"No valid specification of the columns. Only a scalar, list or slice of all integers or all strings, or boolean mask is allowed"**

Does AutoPyTorch only support integer inputs?

**Comment by ravinkohli** [comment]
Hey, thanks for this question. Actually, we have been working on a new version of autopytorch that is available on the branch [`development](https://github.com/automl/Auto-PyTorch/tree/development), for docs, see [this](https://automl.github.io/Auto-PyTorch/development/).  Now we feel it's ready for people to test their workflows with this version. 

So I suggest you to try out your data with the development version. For an example on how to use the API, find it [here](https://automl.github.io/Auto-PyTorch/development/examples/index.html)

**Comment by yashlal** [comment]
Ok thank you @ravinkohli. I am unable to switch over to that version because I am working on Windows. Also, another error I seem to be getting is **"UserWarning: n_components > n_samples. This is not possible"** but the dataset I am inputting has shape (546, 100) so this shouldn't be true. This along with the previous error I mentioned is causing the AutoNetClassification to often return errors when I am trying to run it on my dataset. Is there any way for me to alleviate these problems without switching to a different OS/new development branch.
