### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by bakirillov** [automl/Auto-PyTorch#22]
Hello!

Auto-Pytorch fails with the following error:
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

What am I doing wrong?

**Comment by bakirillov** [comment]
Found out the solution. Just don't use your GPU anywhere else.

**Comment by amirakbarnejad** [comment]
In the [master-old branch](https://github.com/automl/Auto-PyTorch/tree/master-old) it is mentioned that " ... Disable pynisher if you experience issues when using cuda ...". In my case disabling pynisher solved the issue.
