### ISSUE TITLE
Enable minority features coalescense  in autopytorch

### ISSUE THREAD

**Issue by franchuterivera** [automl/Auto-PyTorch#239]
Enable the pipeline to ignore the less frequent class. We should do this in a way that the pipeline can learn this. In other words, we should add a step in the pipeline that can ignore an infrequent features with a certain learnable criterion (maybe something like [this](https://stackoverflow.com/questions/55948491/scikitlearn-remove-less-frequent-categorical-classes)).

**Comment by ravinkohli** [comment]
This issue has been resolved with PR #376
