### ISSUE TITLE
How to check the total number of jobs?

### ISSUE THREAD

**Issue by zym604** [automl/Auto-PyTorch#24]
Hi,

The code often shows that it is doing job XXX, then XXX+1, but I don't know totally how many jobs is it going to take. It is not a big issue, but know the total number of jobs will give me an estimation of remaining time I'll use.

![image](https://user-images.githubusercontent.com/9557009/69110924-0969ae80-0a4a-11ea-9bd3-ab323c030f3a.png)

**Comment by LMZimmer** [comment]
Hey,

the ID comes from the optimizer used as backend by Auto-PyTorch which is [HpBandSter](https://github.com/automl/HpBandSter). The first digit increases for each new stage in the successive halving while the second identifies the job within that stage. The configurations per stage and total number of stages are chosen by HpBandSter based on the given budgets. If you are interested in how they are calculated, see [here](https://github.com/automl/HpBandSter/blob/master/hpbandster/optimizers/bohb.py) (line 101-102 & 136-139, `eta`, `max_budget`, `min_budget` can be set in Auto-PyTorch).

You can also simply specify `max_runtime` in the Auto-PyTorch config to set a time limit.
