### ISSUE TITLE
example jupyter notebook TypeError: get_config_space() got an unexpected keyword argument 'T_mult'

### ISSUE THREAD

**Issue by develooper1994** [automl/Auto-PyTorch#25]
I didn't change anything. I just run all notebook.
I am using Windows 10, cuda 10-update 2 and Python 3.7.5. I have all necessary compliers. Auto-PyTorch successfully installed and imported.
...
# Get the ConfigSpace object with all hyperparameters, conditions, default values and default ranges
hyperparameter_search_space = autonet.get_hyperparameter_search_space()
...

4'th cell traceback:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-3634fd73ae3e> in <module>
      3 
      4 # Get the ConfigSpace object with all hyperparameters, conditions, default values and default ranges
----> 5 hyperparameter_search_space = autonet.get_hyperparameter_search_space()
      6 
      7 # Print all possible configuration options

~\Anaconda3\lib\site-packages\autopytorch-0.0.2-py3.7.egg\autoPyTorch\core\api.py in get_hyperparameter_search_space(self, X_train, Y_train, X_valid, Y_valid, **autonet_config)
    101                                                  Y_valid=Y_valid)["dataset_info"]
    102 
--> 103         return self.pipeline.get_hyperparameter_search_space(dataset_info=dataset_info, **pipeline_config)
    104 
    105     @classmethod

~\Anaconda3\lib\site-packages\autopytorch-0.0.2-py3.7.egg\autoPyTorch\pipeline\base\pipeline.py in get_hyperparameter_search_space(self, dataset_info, **pipeline_config)
    109         for name, node in self._pipeline_nodes.items():
    110             #print("dataset_info" in pipeline_config.keys())
--> 111             config_space = node.get_hyperparameter_search_space(**pipeline_config)
    112             cs.add_configuration_space(prefix=name, configuration_space=config_space, delimiter=ConfigWrapper.delimiter)
    113 

~\Anaconda3\lib\site-packages\autopytorch-0.0.2-py3.7.egg\autoPyTorch\pipeline\nodes\lr_scheduler_selector.py in get_hyperparameter_search_space(self, dataset_info, **pipeline_config)
     56                 continue
     57             lr_scheduler_cs = lr_scheduler_type.get_config_space(
---> 58                 **self._get_search_space_updates(prefix=lr_scheduler_name))
     59             cs.add_configuration_space( prefix=lr_scheduler_name, configuration_space=lr_scheduler_cs, delimiter=ConfigWrapper.delimiter, 
     60                                         parent_hyperparameter={'parent': selector, 'value': lr_scheduler_name})

TypeError: get_config_space() got an unexpected keyword argument 'T_mult'

**Comment by LMZimmer** [comment]
Hey there,

are you on the master or development branch? There recently was a change of hyperparameter names which is probably the reason for this (cosine_annealing was changed to cosine_annealing_with_restarts).

**Comment by develooper1994** [comment]
Which branch i should use?

**Comment by LMZimmer** [comment]
The notebook is meant to be used with the master branch, it will be updated with the next merge.
