### ISSUE TITLE
mlpnet input layer has one less feature

### ISSUE THREAD

**Issue by GautamSridhar** [automl/Auto-PyTorch#26]
Hi,

I recently started using AutoPytorch for discovering normal mlpnets for the regression setting. Unfortunately, if my data has 21 features as in the example, the learned network actually takes only 20 input features. I'm not sure what I am doing wrong, but if I try to use the model for further predictions as a standard pytorch model, it gives errors because of the matrix dimension mismatch. Any solutions to this?

This is my discovered network - 
![image](https://user-images.githubusercontent.com/17831253/69947281-a36f3380-14ed-11ea-99f7-25b279962790.png)

**Comment by LMZimmer** [comment]
For featurized data there is a lot of preprocessing techniques implemented. One of them probably downsamples the data. Could you provide the full configuration?

However, it is probably a good idea to implement a method to extract the preprocessing pipeline in some form for further usage. We should do this in a future release

**Comment by GautamSridhar** [comment]
Thanks for the reply! Turns out it was a preprocessing technique that was downsampling the data. In my configuration, all the options were set active. Setting the preprocessing to none produced the right input size for the architecture. Is there any available documentation other than the example notebook which describes the role of all the options in the configuration?

**Comment by LMZimmer** [comment]
The instances of the autonet classes have a `print_help()` function which gives information about some options. This will become more detailed in the future. In terms of preprocessing options we tried adapted the common terminology so that it should be possible to find documentation about it elsewhere (although it would be nice to have some small guide here).

**Comment by GautamSridhar** [comment]
Thanks! I'll look forward to more documentation then, but it's good enough to be used for my purposes right now. Closing the issue!

**Comment by bunnyfighting** [comment]
@GautamSridhar 

Hi,

When I use the AutoPytorch for searching network, the data was downsampled. However, I used "include_components" to set the preprocessing none, like this "include_components={'preprocessing': ["NoPreprocessor"]}". But it was not work. So how did you set the preprocessing to none produced the right input size for the architecture?
