### ISSUE TITLE
[Enhancement] Make refit() method run in dask

### ISSUE THREAD

**Issue by franchuterivera** [automl/Auto-PyTorch#268]
We can improve the `refit()` method so that it runs like [fit_pipeline](https://towardsdatascience.com/fit-vs-transform-in-scikit-libraries-for-machine-learning-3c70e6300ded)

**Comment by ravinkohli** [comment]
I think you linked the wrong url?

**Comment by ravinkohli** [comment]
This issue will actually also be resolved when resolving #469. I am closing this issue and we can continue the discussion there.
