### ISSUE TITLE
[refactor] Make the logger message rules

### ISSUE THREAD

**Issue by nabenabe0928** [automl/Auto-PyTorch#274]
I will make rules and upload them to Wiki.
Basically, rules will be based on pep8, google style, torch conventions.
The main purposes are to reduce:
1. the variations of messages
2. the time to think about the format

The rules include the usage of single or double quotations and f-string as well.

**Comment by ravinkohli** [comment]
I think you have already opened a PR for this https://github.com/automl/Auto-PyTorch/pull/134

**Comment by ravinkohli** [comment]
It seems like we github rules [here](https://github.com/automl/Auto-PyTorch/pull/378/files#r803873478). Do you think its okay to close this issue @nabenabe0928 ?
