### ISSUE TITLE
Colab Example Request

### ISSUE THREAD

**Issue by RitchieAlpha** [automl/Auto-PyTorch#28]
To test the performance of auto-pytorch, I wish you could offer us an executable colab example, like mnist classification or other simple applications. This may help us a lot to understand how to use your code! 
Thank you for your solid research, look forward to your reply!
Jiale Tan

**Comment by mfeurer** [comment]
@mlindauer created some over at automl.org: https://www.automl.org/events/amir19-key-note-and-automl-hands-on/
