### ISSUE TITLE
Missing datasets in example

### ISSUE THREAD

**Issue by KEggensperger** [automl/Auto-PyTorch#3]
`example/mem_test.py` and all scripts in `examples/real_data` searches for datasets in `<..>/Auto-PyTorch/datasets/` which are not there and thus fail.

```FileNotFoundError: File b'/home/eggenspk/Work/git/Auto-PyTorch/datasets/classification/dataset_28_optdigits.csv' does not exist```

This is not a critical problem, but the datasets could be downloaded automatically when run for the first time.

**Comment by franchuterivera** [comment]
Hello! This problem has been fixed and our examples are rendering nicely in our web page here:
https://automl.github.io/Auto-PyTorch/development/examples/index.html

Thanks for reporting. I am closing this issue as it seems to be resolved.
