### ISSUE TITLE
Imputation issues

### ISSUE THREAD

**Issue by LMZimmer** [automl/Auto-PyTorch#30]
If only the validation split contains NaNs in certain columns, there might be errors.

**Comment by le-dawg** [comment]
Oh, might this be related to my error (works flawlessly on the examples, throws errors on my dataset):

>   File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/nodes/imputation.py", line 29, in <listcomp>
>     dataset_info.categorical_features = [dataset_info.categorical_features[i] for i, is_nan in enumerate(all_nan) if not is_nan]
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

My data is 7352x128x9 ndarray of purely numerical values (9 time series vectors of 128 length per each example).

Is setting validation_split to 0 or 1 going to temporarily fix the issue?

**Comment by weir12** [comment]
Hi
@le-dawg 
I have the same problem as you described.
My data is the shape of [batch_sizes,time_steps,input_sizes] which is conforms to the RNN input data format.
Have you solved the problem now?
Thanks!

**Comment by franchuterivera** [comment]
With the new refactor code in the development branch, this is no longer a problem. For this reason, I am closing this old issue.
