### ISSUE TITLE
[ADD] docker workflow

### ISSUE THREAD

**Issue by ravinkohli** [automl/Auto-PyTorch#315]
Once we are done with release 0.1.0, we should create a GitHub package [here](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages) to push our image to. Also, we should add a workflow to publish the image to `automl` docker account.  For example, [here](https://github.com/automl/auto-sklearn/blob/master/.github/workflows/docker-publish.yml)

**Comment by nabenabe0928** [comment]
solved
