### ISSUE TITLE
Maybe a typo or I don't understand

### ISSUE THREAD

**Issue by achillesliu** [automl/Auto-PyTorch#344]
In `autoPyTorch.pipeline.components.preprocessing.tabular_preprocessing.imputation.SimpleImputer.py`, `SimpleImputer.get_hyperparameter_search_space()` is using `CategoricalHyperparameter` from `ConfigSpace` to add hyperparameter.

I checked codes from `ConfigSpace` and find `NumericalHyperparameter`. Why not use it?

**Comment by eddiebergman** [comment]
While I'm not sure what's going on with the `if` statements there, but, it's a *categorical hyperparameter* and **not** a *numerical hyperparameter* as it selects an imputation strategy between `("mean", "median", "most_frequent","constant_zero")` as seen on [line 76](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L76).

You can see on [line 93](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L93) that it references the `numerical_strategy` of line 76.

**Comment by achillesliu** [comment]
> While I'm not sure what's going on with the `if` statements there, but, it's a _categorical hyperparameter_ and **not** a _numerical hyperparameter_ as it selects an imputation strategy between `("mean", "median", "most_frequent","constant_zero")` as seen on [line 76](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L76).
> 
> You can see on [line 93](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L93) that it references the `numerical_strategy` of line 76.

To me the question is on [line 93](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L93). `add_hyperparameter` function takes 3 parameters. The 2nd and 3rd are correspondingly `hyperparameter` and `hyperparameter_type`. To my understanding the two should be either `numerical_strategy, NumericalHyperparameter` or `categorical_strategy, CategoricalHyperparameter`.

The latter combination is on [line 97](https://github.com/automl/Auto-PyTorch/blob/06e67de5017b4cccad9398e24a3d9f0bd8176da3/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L97) as I expected. But on line 93 it's `numerical_strategy, CatigoricalHyperparameter`. This is where I don't understand.

**Comment by eddiebergman** [comment]
The `numerical_strategy` can be one of a discrete set, `("mean", "median", "most_frequent", "constant_zero")`. This represents a `CategoricalHyperparameter` as there is a fixed set of choices. 

In constrast, a `NumericalHyperparameter` would be a continuous set of choices, for example a number in the range `[0, 1]`.

I hope this makes things clearer?

**Comment by achillesliu** [comment]
Now I see. I checked other usages of `CategoricalHyperparameter` and `NumericalHyperparameter` after your answer. Thank you for the help!
