### ISSUE TITLE
Weird if statements in `SimpleImputer.py`

### ISSUE THREAD

**Issue by eddiebergman** [automl/Auto-PyTorch#345]
I was browsing some code in `SimpleImputer.py` and I really have no idea how this multi-line double if statement with a `0 != 0` in it works? Little cleaning job I guess

* https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py#L91

```python
if len(dataset_properties['numerical_columns']) \
        if isinstance(dataset_properties['numerical_columns'], List) else 0 != 0:
    add_hyperparameter(cs, numerical_strategy, CategoricalHyperparameter)
```

**Comment by nabenabe0928** [comment]
solved
