### ISSUE TITLE
Continuation of Issue#352

### ISSUE THREAD

**Issue by nabenabe0928** [automl/Auto-PyTorch#355]
The issue is the division between multiclass and continuous.
The quick solution is to filter continuous by checking whether labels cover the integer of [0, C).
However, it causes the following issues:
1. numerical class labels of random integers are not allowed
2. 1-indexed class labels are not allowed
3. rank regression will be mis-recognized as multiclass

To address those issues, we need to enhance input_validator or preprocessing BEFORE instantiating dataset class.
At least, we know that the given task is either classification or regression, so we should use this knowledge.

**Comment by ravinkohli** [comment]
It has been resolved with #386
