### ISSUE TITLE
Example on README does not work

### ISSUE THREAD

**Issue by creikey** [automl/Auto-PyTorch#362]
NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://stackoverflow.com

Your issue may already be reported!
Also, please search on the [issue tracker](../) before creating one.

* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

# Issue Description
Copy paste example on readme into properly configured python environment

## Expected Behavior
Accuracy score to be printed at the end of the script

## Current Behavior
Dummy prediction fails

## Error message

```
[WARNING] [2021-12-14 08:49:00,146:Client-Validation] AutoPyTorch previously received features of type <class 'numpy.ndarray'> yet the current features have type <class 'pandas.core.frame.DataFrame'>. Changing the dtype of inputs to an estimator might cause problems
[WARNING] [2021-12-14 08:49:00,209:Client-Validation] AutoPyTorch previously received features of type <class 'numpy.ndarray'> yet the current features have type <class 'pandas.core.frame.DataFrame'>. Changing the dtype of inputs to an estimator might cause problems
[ERROR] [2021-12-14 08:49:02,507:Client-AutoPyTorch:ae1817a6-5cba-11ec-92a6-0242ac1c0002:1] Dummy prediction failed with run state StatusType.MEMOUT and additional info:
error: Memout (used more than 4096 MB).
configuration_origin: DUMMY.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-01226f07b7e6> in <module>()
     19     optimize_metric='accuracy',
     20     total_walltime_limit=500,
---> 21     func_eval_time_limit_secs=50
     22 )
     23 

2 frames
/usr/local/lib/python3.7/dist-packages/autoPyTorch/api/base_task.py in _do_dummy_prediction(self)
    585                 self._logger.error(err_msg)
    586                 # Fail if dummy prediction fails.
--> 587                 raise ValueError(err_msg)
    588 
    589     def _do_traditional_prediction(self, time_left: int, func_eval_time_limit_secs: int) -> None:

ValueError: Dummy prediction failed with run state StatusType.MEMOUT and additional info:
error: Memout (used more than 4096 MB).
configuration_origin: DUMMY.
```

## Your Local environment
* Google colab gpu instance with this ran before copy pasted example from readme:
```
!pip uninstall scipy smac autoPyTorch albumentations
!pip install autoPyTorch
```
* Python, version 3.7.12
* Outputs of `pip freeze` or `conda list`

**Comment by nabenabe0928** [comment]
Hi, I just add a quick comment.

We tried the example in our local environments and it worked,
but we have not tried on the GCP.
Since the tests on GCP are usually more complicated due to various permission issues, please give us some time.

**Comment by ravinkohli** [comment]
@nabenabe0928 what is the status for this?

**Comment by nabenabe0928** [comment]
@creikey Hi, we finished merging [the PR](https://github.com/automl/Auto-PyTorch/pull/386) to fix this issue.
