### ISSUE TITLE
AutoNetImageClassification Example

### ISSUE THREAD

**Issue by Supersak80** [automl/Auto-PyTorch#38]
Thank you for the wonderful work! Could you please provide an example showing how to use the API with the AutoNetImageClassification class? An example using CIFAR-10 would be great!

Thanks!
Sam

**Comment by LMZimmer** [comment]
Hey there and thanks for your interest. We actually have a short tutorial where CIFAR10 is used [here](https://github.com/automl/Auto-PyTorch/blob/master/examples/basics/Auto-PyTorch%20Tutorial.ipynb) :)

**Comment by Supersak80** [comment]
Thank you!
