### ISSUE TITLE
Can we only do hyper parameter search?

### ISSUE THREAD

**Issue by NoOneUST** [automl/Auto-PyTorch#39]

**Comment by LMZimmer** [comment]
Hey,
there is no option such as "do_hpo_only" since you would have to specify an architecture. What you could do of course, is to update the search space to only allow for one architecture (e.g. a mlpnet with 1 layer and 20 units) using the updating api demonstrated on the main page.

**Comment by maxmarketit** [comment]
@LMZimmer Allowing only one architecture seems great idea. And developing it further, I suggest that  we do hyper parameter search with **custom fixed architecture**. 

We can do further to set certain part of architecture fixed and certain part of architecture searched. Anyway for my purpose right now, I would do appreciate if I could do hyperparameter search with my custom pytorch model :)
