### ISSUE TITLE
What are all possible values in the include_components param in TabularClassificationTask

### ISSUE THREAD

**Issue by shabir1** [automl/Auto-PyTorch#419]
What are all possible values in the `include_components` param in `TabularClassificationTask`?
How to run only selected algorithms as in `autosklearn` we are using `include` and `exclude`.

**Comment by ravinkohli** [comment]
Hey, thanks for raising the issue. `include_components` and `exclude_components` work the same way as `include` and `exclude` from autosklearn. Essentially, you can choose any step of the pipeline for example, `encoder` and you need to provide a list of the components you would like to include/exclude, for example, if you dont want to encode the categorical data, you can pass 
```
include_components = {'encoder': ['NoEncoder']}
```. 
You can find more information in our example [here](https://automl.github.io/Auto-PyTorch/master/examples/40_advanced/example_custom_configuration_space.html)
