### ISSUE TITLE
Can we run only RandomForest and KNN from Traditional?, and how?

### ISSUE THREAD

**Issue by shabir1** [automl/Auto-PyTorch#420]
How to run only a few MyTraditionalTabularClassificationPipeline like RandomForest and KNN?

**Comment by ravinkohli** [comment]
Hey, thanks for raising the issue. We currently don't support running only the traditional learners as the main focus of this library is on using deep learning. The traditional classifiers are currently only used to add diversity to the final ensemble created. If you would like to search for these classifiers, I would suggest using auto-sklearn, [here](https://automl.github.io/auto-sklearn/master/).
