### ISSUE TITLE
Disable Preprocessing

### ISSUE THREAD

**Issue by damirpolat** [automl/Auto-PyTorch#431]
From my understanding, the search can include preprocessing. Is there any way to disable preprocessing step when performing the search for "not traditional" pipelines? If so, how does that work? I can't find any documentation for it.

**Comment by ravinkohli** [comment]
Hey,
we allow disabling any of the steps that have choices by including the `Noxxxx`. For example, encoding can be disabled by including `NoEncoder` as the choice for the `EncoderChoice` step. This can be done by using the `include_components` parameter passed to the tasks. You can find an example in [`example_custom_configuration_space`](https://github.com/automl/Auto-PyTorch/blob/06e67de5017b4cccad9398e24a3d9f0bd8176da3/examples/40_advanced/example_custom_configuration_space.py#L76). Let me know if you need further help in customising the search space. 

Do note that we have certain preprocessing in the `TabularInputValidator.py` which includes imputation and ordinal encoding of categorical features. This is necessary as neural networks do not natively support training with categories.
