### ISSUE TITLE
time-series config json file missing when running example code

### ISSUE THREAD

**Issue by RobbyW551** [automl/Auto-PyTorch#456]
NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://stackoverflow.com

Your issue may already be reported!
Also, please search on the [issue tracker](../) before creating one.

* **I'm submitting a ...**
  - [x] bug report

# Issue Description
* When Issue Happens
  1. Running example code of time-series forecasting.
* Steps To Reproduce
  1. install autopytorch-0.2 with pip.
  `pip install autoPyTorch autoPyTorch[forecasting]`
  1. run https://github.com/automl/Auto-PyTorch/blob/master/examples/20_basics/example_time_series_forecasting.py in the auto-pytorch virtual environment.

## Expected Behavior

There should be three config json files in 'config' directory, including **forecasting_init_cfgs.json**
## Current Behavior

**forecasting_init_cfgs.json** is missing after pip installation in the site-package repo of python.
## Error Message
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/robby/miniconda3/envs/auto-pytorch/lib/python3.8/site-packages/autoPyTorch/optimizer/../configs/forecasting_init_cfgs.json'
```
## Your Local environment
* Operating System, version
Ubuntu 20.04
* Python, version
Python 3.8
* Outputs of `pip freeze` or `conda list`
pytorch=1.12+cu116

**Comment by dengdifan** [comment]
Thanks for the bug reporting, the path to the forecasting_init_cfgs.py was not properly installed, we will fix this bug ASAP in the next release.

**Comment by ravinkohli** [comment]
Hi, we have fixed this issue in the latest release.  You can install it using `pip install autoPyTorch==0.2.1`. I am closing this issue for now.
