### ISSUE TITLE
[AssertionError in `fit_pipeline()` when `pipeline_options` is not None

### ISSUE THREAD

**Issue by PhMueller** [automl/Auto-PyTorch#463]
Hi guys, 

I was trying out your fantastic tool and found a small bug.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

# Issue Description
* An exception will be raised when specifying the argument `pipeline_options` in the `fit_pipeline` function. 

* Steps To Reproduce
  1. api = TabularRegressionTask(...)
  2. api.fit_pipeline(..., pipeline_options={'early_stopping': 100})

## Problem/Solution:
[In api/base_task Line 1635-1638](https://github.com/automl/Auto-PyTorch/blob/c138dff1909464110f4d35dfb9c016e724a8c25a/autoPyTorch/api/base_task.py#L1635-L1638)

```python 
pipeline_options = self.pipeline_options.copy().update(pipeline_options) if pipeline_options is not None \
    else self.pipeline_options.copy()

assert pipeline_options is not None
``` 
The `update()` function returns `None`. 

Replacing it with the following would remove the error: 

```python 
pipeline_options = {**self.pipeline_option, **pipeline_options} if pipeline_options is not None \
    else self.pipeline_options.copy()

assert pipeline_options is not None
``` 

Current workaround: 

``` python
api.set_pipeline_config(**{'early_stopping': 50})
api.fit_pipeline(...) # do not specify `pipeline_options` here. 
```

## Your Local environment
* AutoPytorch Version: 0.2 (current master)

**Comment by ravinkohli** [comment]
Hey, thanks for reporting this bug. We'll incorporate this in the next release which should be released very soon.

**Comment by ravinkohli** [comment]
Hi, we have fixed this issue in the latest release.  You can install it using `pip install autoPyTorch==0.2.1`. I am closing this issue for now.
