### ISSUE TITLE
Runtime error: Using a set of choices is prohibited as it can result in non-deterministic behavior.

### ISSUE THREAD

**Issue by Marchphy** [automl/Auto-PyTorch#48]
I came across this colab notebook that demonstrates how to use Auto-Pytorch.

https://colab.research.google.com/drive/1XhWT_crM91J1ay5BzDGWZ-vBLjyKqrEI?usp=sharing

This environment has python3.6.9. And calling the fit method triggers the errors in the images attached. I can also replicate this behavior on my local machine with python3.7.7.

<img width="1346" alt="Screen Shot 2020-05-31 at 1 28 38 AM" src="https://user-images.githubusercontent.com/11534894/83345199-69d18680-a2de-11ea-8bd5-654126b1a6db.png">

**Comment by mlindauer** [comment]
Dear Qi,

Thank you for reporting this issue. It seems to be an incompatibility with the newest version of the configspace package, which we use in AutoPyTorch. 

@LMZimmer Could you please check that this is fixed in the next release? 

Best,
Marius
