### ISSUE TITLE
How to use multi-gpus?

### ISSUE THREAD

**Issue by maxmarketit** [automl/Auto-PyTorch#54]
Thank you for the promising package.

  I wonder how I can use multi-gpus.

  I tinkered with `num_workers` and `torch_num_threads` but nothing seemed to be changed.

  ( I wish I could have a document about configuration ).

  So is there any way to use multiple gpus? or set the default gpu to use other than 0?

**Comment by LMZimmer** [comment]
There are a few ways of using parallelism:

i) Multiple workers: Start Auto-PyTorch in multiple threads, where all have the same `run_id` and different `task_id`. The worker with `task_id=1` will be the master. This is done in the [ensemble example](https://github.com/automl/Auto-PyTorch/tree/master/examples/ensemble).

ii) For image data when a thread has more than one GPU it will automatically apply PyTorchs `nn.DataParallel`.

iii) Setting the number of threads for data loading in the autonet config will set the corresponding value in `nn.DataLoader`.

**Comment by astro-kevin** [comment]
The Ensemble example link is broken. Is there an equivalent in the current examples?
