### ISSUE TITLE
Can I set manually the default value for hyper parameters

### ISSUE THREAD

**Issue by maxmarketit** [automl/Auto-PyTorch#58]
I found how to set hyperparameter space

```
from autoPyTorch import HyperparameterSearchSpaceUpdates
search_space_updates = HyperparameterSearchSpaceUpdates()

search_space_updates.append(node_name="NetworkSelector",
                            hyperparameter="mlpnet:num_layers",
                            value_range=[1,4], log=False)
```

But is there any way to set the default value for the hyperparameters?

I look into `search_space_updates.append` and no more parameters are possible

I am talking about the default from `get_hyperparameter_search_space()`.
I guess it is the starting point for searching over hyperparameters.

Thank you in advance

**Comment by LMZimmer** [comment]
Hi,
the default is actually generated by the ConfigSpace object. You can find the Cython source code in the [ConfigSpace](https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/configuration_space.pyx) repo. However, the default config is not used as a starting point for the optimization. The first configurations are sampled randomly from the ConfigSpace object by [BOHB](https://github.com/automl/HpBandSter/blob/841db4b827f342e5eb7f725723ea6461ac52d45a/hpbandster/optimizers/config_generators/bohb.py#L125).
