### ISSUE TITLE
PowerTransformer for Feature Preprocessing

### ISSUE THREAD

**Issue by mlindauer** [automl/Auto-PyTorch#6]
Hi,

some of our internal benchmarks showed that sometimes a [PowerTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PowerTransformer.html) can substantially improve the performance of our DNNs on featurized data. @urbanmatthias could you please add that to AutoPyTorch.

Thanks,
Marius

**Comment by urbanmatthias** [comment]
Hi,

the PowerTransformer is now available in the develop branch.

Cheers,
Matthias
