### ISSUE TITLE
Unable to import Autopytorch in Windows10

### ISSUE THREAD

**Issue by saiprasadbarke** [automl/Auto-PyTorch#68]
Hello,

I followed the instructions on the GitHub page for installing Autopytorch on my local machine and I was successful in doing so. The problem arises when I try to import auto-PyTorch in my Jupyter notebook. 

**The error is as follows:** 

![error autopytorch](https://user-images.githubusercontent.com/22209943/94985593-566a4c80-0558-11eb-8141-4bb082cf7016.JPG)

**The terminal output is as follows:** 
[terminal output.txt](https://github.com/automl/Auto-PyTorch/files/5321242/terminal.output.txt)

I am using a windows10 machine and python 3.8 in a virtual environment.

**Comment by vahin** [comment]
@saiprasadbarke Try uninstalling it and then install it using this command: `pip install git+https://github.com/automl/Auto-PyTorch` 

Also don't forget to install IPython: `pip install IPython`

**Comment by saiprasadbarke** [comment]
Hello,

The issue has resolved itself. I am using VSCode as my default IDE and I also run python notebooks in it. The issue was that my ipynb kernel pointed to my conda installation (no autopytorch was installed there), whereas I had defined a venv to run my actual project from(Normal python installation in a venv with autopytorch installed).

**Comment by Oussamab21** [comment]
Hi saiprasadbarke, I can t install autopytorch on windows 10 because torch vision version 0.8.2 is not available for windows did you face this issue ?

**Comment by saiprasadbarke** [comment]
No i did not face this. For me I had to install the dependencies separately as something was breaking with wheel in pip when u installed using requirements.txt
