### ISSUE TITLE
Question about AutoNetImageClassification

### ISSUE THREAD

**Issue by RodionovDenis** [automl/Auto-PyTorch#69]
Hello! Please tell me, is it possible to make my AutoNetImageClassification model contain only one-dimensional convolutions Conv1d? If so, how do you set the search space parameters in this case?

**Comment by LMZimmer** [comment]
Hi, I updated the bounds for the kernel size (https://github.com/automl/Auto-PyTorch/blob/e22a3745ff9a9e4bb7aefa3f58c3fe6c296a6340/autoPyTorch/components/networks/image/convnet.py#L82) which should allow setting it to 1.
