### ISSUE TITLE
Multithreading problems with Image classification

### ISSUE THREAD

**Issue by dwoiwode** [automl/Auto-PyTorch#71]
When you try to set up a minimum working example for image classification with the preset=**full_cs** like in the jupyter notebook, an AttributeError is raised:
```AttributeError: Can't pickle local object 'CreateImageDataLoader.fit.<locals>.<lambda>'```

This error is due to the lambda-Functions in [create_image_dataloader.py](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/pipeline/nodes/image/create_image_dataloader.py) as local functions inside of functions cannot be pickled.

To fix this error, a seperate function has to be created:
```
def transform_int64(y):
    return y.astype(np.int64)
```
which is then be used instead of the lambda-function.

Fixing this error yields to another error in the file [activations.py](https://github.com/automl/Auto-PyTorch/blob/master/autoPyTorch/components/networks/activations.py):
```ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them```
`inspect.getargspec()` is [depreceated since version 3.0](https://docs.python.org/3/library/inspect.html#inspect.getargspec) and changing this function to the improved version `inspect.getfullargspec()` solves this problem.

Furthermore the MWE has to be encapsulated by using `if __name__ == "__main__"` to avoid recursion in multithreading imports.

PR to fix this issues coming soon

**Comment by LMZimmer** [comment]
Fixed with PR #73 . Thank you for the contribution!
