### ISSUE TITLE
Invalid search space update in AutoNetImageClassification tiny_cs-preset: cosine_annealing_with_restarts:T_max

### ISSUE THREAD

**Issue by dwoiwode** [automl/Auto-PyTorch#72]
When you try to set up a minimum working example for image classification with the preset=**tiny_cs** or **medium_cs** like in the jupyter notebook, a ValueError is raised:
```ValueError: Invalid search space update given: cosine_annealing_with_restarts:T_max```

This error does not happen with preset=full_cs.

The MWE as a seperate example file can be found in
https://github.com/dwoiwode/Auto-PyTorch/blob/image_classification_example/examples/basics/image_classification.py

**Comment by LMZimmer** [comment]
This was caused by hardcoded (unnecessary) search space updates in the AutoNetImage class and is now fixed
