### ISSUE TITLE
Auto-Pytorch Tabular

### ISSUE THREAD

**Issue by janakan97** [automl/Auto-PyTorch#74]
As the project is an initiation to the paper Auto-Pytorch tabular why there is no any implementation or dataset related to the dataset

**Comment by LMZimmer** [comment]
Hey, I assume you are referring to the LCBench dataset from our [paper](https://arxiv.org/abs/2006.13799). We have another repository for [LCBench](https://github.com/automl/LCBench) with instructions on how to download the dataset and with an API to query from it.

In case you are looking for code for the final experiments from the APT paper you can find it under `examples/ensemble`, we also updated the README to point to this now.
