### ISSUE TITLE
If only performing hyperparameter tuning, is Auto-PyTorch the same as BOHB?

### ISSUE THREAD

**Issue by 2533245542** [automl/Auto-PyTorch#75]
I noticed that BOHB is the core Bayesian optimization engine for Auto-PyTorch, so if I only want to perform hyperparameter tuning on a fixed structure neural network without any sort of warm-starting, does Auto-PyTorch perform the same as BOHB?

**Comment by LMZimmer** [comment]
Hey, you can specify the `algorithm` parameter in the pipeline config. Per default, this is set to `bohb`, which is plain BOHB without any warmstarting. For warmstarting, you need to use a search space for which portfolios are supported and specify `algorithm=portfolio_bohb`.

So, in summary, if you choose a search space that has a fixed architecture, it will per default optimize using "normal BOHB".
