### ISSUE TITLE
Ensure training each backbone and head attains good accuracy 

### ISSUE THREAD

**Issue by ravinkohli** [automl/Auto-PyTorch#79]
Currently, in the test for networks ([here](https://github.com/automl/Auto-PyTorch/blob/2e7b462c8a75110115f7fcb0115f8cf745f4b6e3/test/test_pipeline/components/test_setup_networks.py#L50)) combinations of backbone and head do not achieve 80% accuracy with the default configuration. We would like to fix the search space with good defaults so as all the combinations achieve at least 80%. 
_Originally posted by @franchuterivera in https://github.com/automl/Auto-PyTorch/pull/78#discussion_r565556229_

**Comment by franchuterivera** [comment]
This has been addressed by #82
