### ISSUE TITLE
GPU Optimized

### ISSUE THREAD

**Issue by etetteh** [automl/Auto-PyTorch#9]
Hello,

So, I have a quick question. Is auto-pytorch optimized (written) to run a GPU automatically or I need to call cuda=True in the algorithm, say AutoNetClassification?

I am asking, because even when I pass cuda=True, when running on a GPU enabled instance, I don't see any difference in time taken as compared to just running on a CPU.

**Comment by urbanmatthias** [comment]
Hi,

cuda=True is the default setting. It will automatically be disabled if cuda is not available (torch.cuda.is_available()).

Hope this helps.

Best,

Matthias

**Comment by etetteh** [comment]
Okay @urbanmatthias. Thank you.

Sincerely,
Enoch
